name: Deploy Laravel Application

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  cd:
    name: Continuous Deployment (VPS via SSH)
    if: github.event_name == 'push' && github.ref == 'refs/heads/trunk'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            DEPLOY_DIR="/home/github/deploy/"${{ github.repository }}

            echo "==> Verificar directorio de despliegue"
            if [ ! -d "$DEPLOY_DIR" ]; then
              echo "==> Creando directorio de despliegue"
              mkdir -p "$DEPLOY_DIR"
            else
              echo "==> Directorio de despliegue ya existe"
            fi

            cd "$DEPLOY_DIR"

            echo "==> Verificando estado de repositorio"
            if [ ! -d ".git" ]; then
              echo "==> Clonando repositorio completo"
              cd ../
              git clone https://github.com/${{ github.repository }}.git .
            else
              echo "==> Sincronizando repositorio"
              git fetch origin
              git reset --hard origin/trunk
            fi

            REPO=${{ github.repository }}
            FILE="${REPO//\//_}"
            ENV="/home/github/deploy/env/${FILE}"
            
            cd ../

            echo "==> Verificando archivo de entorno .env..."
            if [ -f "$ENV" ]; then
              cp "$ENV" "$REPO/.env"
              echo "==> Archivo de configuraciones copiado."  
            else
              echo "==> No se encontro el archivo de configuraciones $ENV"
              return 1
            fi

            echo "==> Construyendo y desplegando contenedores Docker..."
            docker compose -f docker-compose.prod.yml up --build -d

            echo "==> Ejecutando migraciones de base de datos..."
            docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force

            echo "==> Optimizando caché de Laravel..."
            docker compose -f docker-compose.prod.yml exec -T app php artisan config:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan route:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan view:cache

            echo "==> Limpiando imágenes de Docker no utilizadas..."
            docker image prune -f

            echo "==> ¡Despliegue completado exitosamente!"
