name: Deploy Laravel Application

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  cd:
    name: Continuous Deployment (VPS via SSH)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/trunk')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code || github.ref == 'refs/heads/trunk'
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            DEPLOY_DIR="/home/github/desploy"

            echo "==> Verificar directorio de despliegue"
            if [ ! -d  $DEPLOY_DIR ]; then
              echo "==> Creando directorio de despliegue"
              mkdir -p $DEPLOY_DIR
            else
              echo "==> Directorio de  despliegue ya existe"
            fi

            cd $DEPLOY_DIR

            echo "==> Verificando estado de repositorio"
            if [ ! -d ${{ github.repository }} ]; then
              echo "==> Clonando repositorio completo"
              git clone https://github.com/${{ github.repositorio }}.git .
            else
              echo "==> Sincronizando repositorio"
              cd ${{ github.repository }}
              git fetch origin
              git reset --hard origin/trunk
              cd ../
            fi

            echo "==> Verificando archivo de entorno .env..."
            if [ ! -f ${{ github.repository }}"/.env" ]; then
              if [ -f ${{ github.repository }} ]; then
                cp ${{ github.repository }} .env
                echo "==> Archivo de configuraciones ENV copiado"
              else
                echo "==> No se enontro un archivo de variables de entorno para configurar el entorno"
                return 1
              fi
            fi

            cd ${{ github.repository }}

            echo "==> Construyendo y desplegando contenedores Docker..."
            docker compose -f docker-compose.prod.yml up --build -d

            echo "==> Ejecutando migraciones de base de datos..."
            docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force

            echo "==> Optimizando caché de Laravel..."
            docker compose -f docker-compose.prod.yml exec -T app php artisan config:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan route:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan view:cache

            echo "==> Limpiando imágenes de Docker no utilizadas..."
            docker image prune -f

            echo "==> ¡Despliegue completado exitosamente!"
